### ISSUE TITLE
Usage 

### ISSUE THREAD

**Issue by vivekjj** [Li-Ming-Fan/OCR-CRNN-CTPN#3]
Hello - Would it be possible to provide simple usage notes for this? Eg. command to train, command to run demo, etc... Do you know how much faster this implementation is vs tesseract w/ OpenCL?

Thanks

**Comment by Li-Ming-Fan** [comment]
Hello, sorry be late to respond. 2018-02-16 was Spring Festival. Wish you a happy Chinese new year.

I have added some description about the usage in the repo. 

Actually I did not compared this implementation with tesseract.  In my experience with tesseract, tesseract is very good, as for detection.
