### ISSUE TITLE
Can you please provide any of your best pre-trained model and demo.py file and also procedure of how to use it?

### ISSUE THREAD

**Issue by arsalan993** [Li-Ming-Fan/OCR-CRNN-CTPN#4]

**Comment by Li-Ming-Fan** [comment]
Hello, sorry be late to respond. 2018-02-16 was Spring Festival. Wish you a happy Chinese new year.

I have added some description about the usage in the repo.

CTPN is easy to train. With just 1000 steps, you can get a not bad model.
